### ISSUE TITLE
Create Robolectric Extension

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/kotest-android#2]
Related: https://github.com/kotest/kotest/issues/3505 
Archived Kotest repository: https://github.com/kotest/kotest-extensions-robolectric

**Comment by jkasten2** [comment]
@LeoColman This would be really nice to have! I am a user of both Kotest and Robolectric and trying to find any solutions to get them to work together in the same test class.

## Attempted workarounds
I attempt to use `kotest-robolectric-extension` (was official but no longer supported) and applied a "patch" to get it working but its not fully working: https://github.com/kotest/kotest/issues/2717#issuecomment-1949288110

## kotest-android with Robolectric 
Back to the topic here, what do you think it would take to get this plugin working with Robolectric? Interested on what you think has to be done, as it's something I am interested attempting, but looking for help.

**Comment by LeoColman** [comment]
There is one specific class in Robolectric that is very hard to understand and plug into.

I'm the original author of the Robolectric extension, and it took me a lot of time to understand the main driver from Robolectric, `RobolectricTestRunner`. After I managed to put something up, it changed and broke the extension and I've never had the capacity to give it another try.


---

Once you are able to get inside Robolectric's environment, Kotest works as expected.

https://github.com/kotest/kotest-extensions-robolectric/blob/9b5779d0881d56af5da30661ddf7272e06bcc7d7/extensions-robolectric/src/main/kotlin/io/kotest/extensions/robolectric/RobolectricExtension.kt#L43


The idea is that the test must be wrapped around to whatever it is that Robolectric uses to execute the tests

**Comment by jkasten2** [comment]
@LeoColman Thanks for the help here! I looked through `RobolectricTestRunner` and Robolectric's `SandboxTestRunner` and found a key difference. `kotest-robolectric-extension` was not calling `runOnMainThread` like [Robolectric's SandboxTestRunner](https://github.com/robolectric/robolectric/blob/robolectric-4.11.1/junit/src/main/java/org/robolectric/internal/SandboxTestRunner.java#L251) was. Adding that got me up and running and put extra details and the exact code in this comment https://github.com/kotest/kotest/issues/2717#issuecomment-1955975350.

**Comment by LeoColman** [comment]
Cool @jkasten2!
Whenever I have the chance I'll publish an artifact with the fixed version!

**Comment by LeoColman** [comment]
@jkasten2 Could you share the full code of the extension you wrote? I'm having a bit of a hard time trying to change from the old model as it was Spec-based, not test based

**Comment by jkasten2** [comment]
@LeoColman here is the full set of source I have been using:
https://github.com/jkasten2/patches-to-kotest-robolectric-extension/tree/master/patched-kotest-robolectric-extension/src/main/java/com/example/patched_kotest_robolectric_extension


The repo includes a full Android project, and you can go back a commit to see the one of the test that fails pass later after the changes:
https://github.com/jkasten2/patches-to-kotest-robolectric-extension/tree/master

The changes were much more than I thought originally, I took `kotest-robolectric-extension/master` and copied my full set of changes over the top in this commit:
https://github.com/jkasten2/patches-to-kotest-robolectric-extension/commit/7c9c8704627b3af852e1fdfd695682c7e12604f7


Hopefully this is helpful, but let me know if you need any more detail, or want to to hunt down the differences a bit better.

**Comment by LeoColman** [comment]
Thanks a lot @jkasten2 !

Closing this issue as released on https://github.com/LeoColman/kotest-android/commit/7c1a520c3fdd850eaaec149e10017aa3093d6753

**Comment by jkasten2** [comment]
@LeoColman Awesome!, this is very helpful we so don't have need to keep running with a locally patched copy. This helps us get with the complexity of the tests in our project and we can get patches from the community easier now!

I tested out `br.com.colman:kotest-extensions-android:0.1.1` with `org.robolectric:robolectric:4.8.1` and `io.kotest:kotest-runner-junit5:5.8.0`, it's all working together for me.
