### ISSUE TITLE
Missing jars in maven central for kotest-extensions-android

### ISSUE THREAD

**Issue by psiska** [LeoColman/kotest-android#4]
Hello,

I was about to try using kotest-extensions-android, but I had a problem setting it up. 
Eventually I've found out that jar are not present in maven central. Only javadoc and sources jar. 

[kotest-extensions-android at repo1.maven.org](https://repo1.maven.org/maven2/br/com/colman/kotest-extensions-android/0.1.0/)
I have noticed similar problem for [kotest-assertions-android](https://repo1.maven.org/maven2/br/com/colman/kotest-assertions-android/1.1.0/)

Is it possible to deploy binary jars as well, please?

Also thanks for the project :)

**Comment by LeoColman** [comment]
Thanks for the report!

A fix is on the way :)

**Comment by LeoColman** [comment]
New artifacts released, please take a look ;)
